In [1]:
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [3]:
df=pd.read_csv("/content/BL (1).csv")
df

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0    LP001003   Male     Yes           1      Graduate            No   
1    LP001005   Male     Yes           0      Graduate           Yes   
2    LP001006   Male     Yes           0  Not Graduate            No   
3    LP001008   Male      No           0      Graduate            No   
4    LP001011   Male     Yes           2      Graduate           Yes   
..        ...    ...     ...         ...           ...           ...   
499  LP001248   Male      No           0      Graduate            No   
500  LP001253   Male     Yes           5      Graduate           Yes   
501  LP001255   Male      No           0      Graduate            No   
502  LP001256   Male      No           0      Graduate            No   
503  LP001259   Male     Yes           1      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583               1508         128               360   
1               3000                  0          66               360   
2               2583               2358         120               360   
3               6000                  0         141               360   
4               5417               4196         267               360   
..               ...                ...         ...               ...   
499             3500                  0          81               300   
500             5266               1774         187               360   
501             3750                  0         113               480   
502             3750               4750         176               360   
503             1000               3022         110               360   

     Credit_History Property_Area  Loan_Status  
0                 1         Rural            0  
1                 1         Urban            1  
2                 1         Urban            1  
3                 1         Urban            1  
4                 1         Urban            1  
..              ...           ...          ...  
499               1     Semiurban            1  
500               1     Semiurban            1  
501               1         Urban            0  
502               1         Urban            0  
503               1         Urban            0  

[504 rows x 13 columns]

In [4]:
df.info

<bound method DataFrame.info of       Loan_ID Gender Married  Dependents     Education Self_Employed  \
0    LP001003   Male     Yes           1      Graduate            No   
1    LP001005   Male     Yes           0      Graduate           Yes   
2    LP001006   Male     Yes           0  Not Graduate            No   
3    LP001008   Male      No           0      Graduate            No   
4    LP001011   Male     Yes           2      Graduate           Yes   
..        ...    ...     ...         ...           ...           ...   
499  LP001248   Male      No           0      Graduate            No   
500  LP001253   Male     Yes           5      Graduate           Yes   
501  LP001255   Male      No           0      Graduate            No   
502  LP001256   Male      No           0      Graduate            No   
503  LP001259   Male     Yes           1      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583          

In [5]:
df["Dependents"].unique()

array([1, 0, 2, 5, 6, 4])

In [6]:
df["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [7]:
df["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [8]:
df["Property_Area"].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [9]:
df["Married"].unique()

array(['Yes', 'No'], dtype=object)

In [10]:
df["Loan_ID"].unique()

array(['LP001003', 'LP001005', 'LP001006', 'LP001008', 'LP001011',
       'LP001013', 'LP001014', 'LP001018', 'LP001020', 'LP001024',
       'LP001028', 'LP001029', 'LP001030', 'LP001032', 'LP001036',
       'LP001038', 'LP001043', 'LP001046', 'LP001047', 'LP001066',
       'LP001068', 'LP001073', 'LP001086', 'LP001095', 'LP001097',
       'LP001098', 'LP001100', 'LP001112', 'LP001114', 'LP001116',
       'LP001119', 'LP001120', 'LP001131', 'LP001138', 'LP001144',
       'LP001146', 'LP001151', 'LP001155', 'LP001157', 'LP001164',
       'LP001179', 'LP001186', 'LP001194', 'LP001195', 'LP001197',
       'LP001198', 'LP001199', 'LP001205', 'LP001206', 'LP001207',
       'LP001222', 'LP001225', 'LP001228', 'LP001233', 'LP001238',
       'LP001241', 'LP001243', 'LP001245', 'LP001248', 'LP001253',
       'LP001255', 'LP001256', 'LP001259'], dtype=object)

In [11]:
df.drop(['Loan_ID'], axis = 1, inplace = True)

In [12]:
df.isnull()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0     False    False       False      False          False            False   
1     False    False       False      False          False            False   
2     False    False       False      False          False            False   
3     False    False       False      False          False            False   
4     False    False       False      False          False            False   
..      ...      ...         ...        ...            ...              ...   
499   False    False       False      False          False            False   
500   False    False       False      False          False            False   
501   False    False       False      False          False            False   
502   False    False       False      False          False            False   
503   False    False       False      False          False            False   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                False       False             False           False   
1                False       False             False           False   
2                False       False             False           False   
3                False       False             False           False   
4                False       False             False           False   
..                 ...         ...               ...             ...   
499              False       False             False           False   
500              False       False             False           False   
501              False       False             False           False   
502              False       False             False           False   
503              False       False             False           False   

     Property_Area  Loan_Status  
0            False        False  
1            False        False  
2            False        False  
3            False        False  
4            False        False  
..             ...          ...  
499          False        False  
500          False        False  
501          False        False  
502          False        False  
503          False        False  

[504 rows x 12 columns]

In [13]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [14]:
df.shape

(504, 12)

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])
df["Married"] = le.fit_transform(df["Married"])
df["Education"] = le.fit_transform(df["Education"])
df["Self_Employed"] = le.fit_transform(df["Self_Employed"])

In [16]:
df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           1          0              0             4583   
1         1        1           0          0              1             3000   
2         1        1           0          1              0             2583   
3         1        0           0          0              0             6000   
4         1        1           2          0              1             5417   
..      ...      ...         ...        ...            ...              ...   
499       1        0           0          0              0             3500   
500       1        1           5          0              1             5266   
501       1        0           0          0              0             3750   
502       1        0           0          0              0             3750   
503       1        1           1          0              1             1000   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                 1508         128               360               1   
1                    0          66               360               1   
2                 2358         120               360               1   
3                    0         141               360               1   
4                 4196         267               360               1   
..                 ...         ...               ...             ...   
499                  0          81               300               1   
500               1774         187               360               1   
501                  0         113               480               1   
502               4750         176               360               1   
503               3022         110               360               1   

    Property_Area  Loan_Status  
0           Rural            0  
1           Urban            1  
2           Urban            1  
3           Urban            1  
4           Urban            1  
..            ...          ...  
499     Semiurban            1  
500     Semiurban            1  
501         Urban            0  
502         Urban            0  
503         Urban            0  

[504 rows x 12 columns]

In [17]:
x = df.iloc[:,0:11].values
x

array([[1, 1, 1, ..., 360, 1, 'Rural'],
       [1, 1, 0, ..., 360, 1, 'Urban'],
       [1, 1, 0, ..., 360, 1, 'Urban'],
       ...,
       [1, 0, 0, ..., 480, 1, 'Urban'],
       [1, 0, 0, ..., 360, 1, 'Urban'],
       [1, 1, 1, ..., 360, 1, 'Urban']], dtype=object)

In [18]:
y = df.iloc[:,11:12].values

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[10])],remainder = "passthrough")
x = np.array(ct.fit_transform(x))
x


array([[1.0, 0.0, 0.0, ..., 128, 360, 1],
       [0.0, 0.0, 1.0, ..., 66, 360, 1],
       [0.0, 0.0, 1.0, ..., 120, 360, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 113, 480, 1],
       [0.0, 0.0, 1.0, ..., 176, 360, 1],
       [0.0, 0.0, 1.0, ..., 110, 360, 1]], dtype=object)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [21]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

In [22]:
x_train

array([[-0.35895897, -0.74161985,  0.93977528, ..., -0.99914124,
         0.21613438,  0.43045803],
       [-0.35895897,  1.34839972, -1.06408418, ...,  2.97441716,
         0.21613438,  0.43045803],
       [-0.35895897,  1.34839972, -1.06408418, ..., -0.57187689,
         0.21613438,  0.43045803],
       ...,
       [-0.35895897, -0.74161985,  0.93977528, ..., -0.21582327,
        -5.29666034,  0.43045803],
       [-0.35895897, -0.74161985,  0.93977528, ..., -0.287034  ,
         0.21613438,  0.43045803],
       [-0.35895897, -0.74161985,  0.93977528, ...,  0.05477748,
         0.21613438,  0.43045803]])

In [23]:
x_test

array([[-0.35895897,  1.34839972, -1.06408418, ...,  0.05477748,
         0.21613438,  0.43045803],
       [-0.35895897, -0.74161985,  0.93977528, ...,  0.05477748,
         0.21613438,  0.43045803],
       [-0.35895897, -0.74161985,  0.93977528, ..., -0.287034  ,
         0.21613438, -2.32310684],
       ...,
       [-0.35895897, -0.74161985,  0.93977528, ..., -0.38672901,
         2.42125227,  0.43045803],
       [-0.35895897, -0.74161985,  0.93977528, ...,  2.44745781,
         0.21613438,  0.43045803],
       [ 2.78583373, -0.74161985, -1.06408418, ..., -0.07340182,
         0.21613438,  0.43045803]])

In [24]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10,activation = "relu"))
ann.add(tf.keras.layers.Dense(units=8,activation = "relu"))
ann.add(tf.keras.layers.Dense(units=6,activation = "relu"))
ann.add(tf.keras.layers.Dense(units=1,activation = "sigmoid"))

In [25]:
ann.compile(optimizer = "adam",loss="binary_crossentropy",metrics=["accuracy"])
ann.fit(x_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
13/13 [==============================] - 1s 2ms/step - loss: 0.6490 - accuracy: 0.5608
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6231 - accuracy: 0.6427
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6014 - accuracy: 0.6600
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5790 - accuracy: 0.7221
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5572 - accuracy: 0.7866
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5340 - accuracy: 0.7965
Epoch 7/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5087 - accuracy: 0.7990
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4814 - accuracy: 0.7965
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4579 - accuracy: 0.7940
Epoch 10/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4317 - accuracy: 0.7940
Epoch 11/

In [26]:
y_pred = ann.predict(x_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]


In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

[[35  0]
 [ 0 66]]
1.0
